name: Build & Run Automated Tests

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'
        
    - name: Restore dependencies
      run: dotnet restore MafiaGameBackend.slnx
      
    - name: Build Solution
      run: dotnet build MafiaGameBackend.slnx --no-restore -c Release
      
    - name: Execute Automated xUnit Tests
      run: dotnet test MafiaGameBackend.slnx --no-build -c Release --verbosity normal
